name: Wheel

on: [push]

jobs:
  wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install build
      - name: Build wheel
        run: python3 -m build -w
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.whl
